### ISSUE TITLE
Support for BurntSushi/erd relationship syntax

### ISSUE THREAD

**Issue by stijnherreman** [mikkel-ol/vsc-er-syntax-highlighting#1]
https://github.com/BurntSushi/erd uses `?` instead of `0` for zero-or-one, but the current relationship regex does not recognise that syntax. Would you mind changing it from `".*[10\\*\\+]--[10\\*\\+]\\s*\\w+"` to `".*[10\\*\\+\\?]--[10\\*\\+\\?]\\s*\\w+"`?

Some context: https://github.com/kaishuu0123/erd-go is based on https://github.com/BurntSushi/erd and https://github.com/unok/erdm.

* erd-go uses `0`for zero-or-one
* erd uses `?` for zero-or-one
* erdm uses `0..1` for zero-or-one
*  https://en.wikipedia.org/wiki/Cardinality_(data_modeling) lists `0..1` and `?` for zero-or-one

**Comment by mikkel-ol** [comment]
I updated to version `0.4.0` with support for all cardinalities.

Thank you for your feedback.
